import { createContext, useContext } from "react";

export type AdminLocale = "en" | "zh-CN" | "ko";
type MessageKey = keyof typeof messages.en;

const messages = {
  en: {
    "nav.overview": "Overview", "nav.plugins": "Plugins", "nav.jobs": "Tasks", "nav.history": "History", "nav.catalog": "Catalog", "nav.speed": "Speed test", "nav.notifications": "Notifications", "nav.components": "Components", "nav.media": "Media roots", "nav.keys": "Entry keys", "nav.security": "Security", "nav.users": "Users", "nav.audit": "Audit events", "nav.signOut": "Sign out",
    "login.title": "CarMediaHub Core", "login.subtitle": "Sign in to your local deployment.", "login.username": "Username", "login.password": "Password", "login.otp": "Authenticator or recovery code", "login.submit": "Sign in", "login.failed": "Sign-in failed", "login.otpRequired": "Enter your authenticator or recovery code",
    "overview.applications": "Applications", "overview.components": "Managed components", "overview.gateway": "Gateway", "overview.healthy": "Healthy", "overview.applicationList": "Applications", "overview.catalog": "Managed component catalog", "overview.name": "Name", "overview.category": "Category", "overview.route": "Route", "overview.vehicle": "Vehicle", "overview.supported": "Supported", "overview.desktop": "Desktop", "overview.component": "Component", "overview.kind": "Kind", "overview.version": "Version", "overview.status": "Status", "overview.executable": "Executable identifier",
    "security.account": "Account security", "security.authenticator": "Authenticator", "security.enabled": "Enabled", "security.disabled": "Not enabled", "security.setup": "Set up authenticator", "security.enabledHint": "Authenticator protection is enabled", "security.enabledDescription": "Use an authenticator code or one unused recovery code when signing in.", "security.password": "Change password", "security.currentPassword": "Current password", "security.newPassword": "New password", "security.passwordInvalid": "Current password is invalid or the new password is too short", "security.passwordChanged": "Password changed; other sessions were signed out", "security.preferences": "Platform preferences", "security.language": "Language", "security.timeZone": "Time zone", "security.theme": "Theme", "security.density": "Density", "security.system": "System", "security.light": "Light", "security.dark": "Dark", "security.comfortable": "Comfortable", "security.compact": "Compact", "security.updated": "Platform preferences updated", "security.updateFailed": "Unable to update platform preferences", "security.setupDescription": "Enter this secret in an authenticator application, then confirm the current six-digit code.", "security.verificationCode": "Verification code", "security.sixDigits": "Enter a six-digit code", "security.invalidCode": "The verification code is invalid", "security.saveCodes": "Save recovery codes", "security.savedCodes": "I saved these codes", "security.codesWarning": "Each recovery code works once. They will not be shown again.",
    "common.add": "Add", "common.list": "List", "common.component": "Component", "common.components": "Components", "common.version": "Version", "common.executable": "Executable", "common.health": "Health", "common.action": "Action", "common.check": "Check", "common.revoke": "Revoke", "common.status": "Status", "common.kind": "Kind", "common.catalog": "Catalog", "common.platforms": "Supported platforms", "common.installed": "Installed", "common.serviceBinding": "Service binding", "common.serviceBindings": "Service bindings", "common.addServiceBinding": "Add service binding", "common.serviceBindingCreated": "Service binding created", "common.serviceBindingCreateFailed": "Unable to create service binding", "common.serviceBindingUnreachable": "Service binding is unreachable", "common.serviceBindingRevoked": "Service binding revoked", "common.serviceBindingRevokeFailed": "Unable to revoke service binding", "common.reachable": "Reachable", "common.scope": "Scope", "common.authorizedInstallations": "Authorized plugin installations", "common.pluginInstallation": "Plugin installation", "common.name": "Name", "common.endpoint": "HTTP(S) endpoint", "common.coreGlobal": "Core global", "common.noneDeclared": "None declared", "common.username": "Username", "common.temporaryPassword": "Temporary password", "common.role": "Role", "common.member": "Member", "common.administrator": "Administrator", "common.organizationUsers": "Organization users", "common.locale": "Locale", "common.active": "Active", "common.revoked": "Revoked", "common.userAdded": "User added", "common.userAddFailed": "Unable to add user", "common.userRevokeFailed": "Unable to revoke user", "common.lastAdmin": "At least one administrator must remain active", "common.signOut": "Sign out", "common.mediaRoot": "Media root", "common.mediaRoots": "Media roots", "common.selectedDirectory": "Selected directory", "common.added": "Added", "common.mediaRootAdded": "Media root added", "common.mediaRootAddFailed": "Unable to add media root", "common.mediaRootRevokeFailed": "Unable to revoke media root",
    "plugins.install": "Install plugin manifest", "plugins.manifest": "Manifest JSON", "plugins.installSuccess": "Plugin installation registered", "plugins.manifestRejected": "Manifest was rejected", "plugins.invalidJson": "Enter valid manifest JSON", "plugins.list": "Plugin installations", "plugins.package": "Package", "plugins.runtime": "Runtime", "plugins.capabilities": "Granted capabilities", "plugins.installation": "Installation", "plugins.worker": "Worker", "plugins.attempts": "Attempts", "plugins.export": "Export data", "plugins.exported": "Plugin data exported", "plugins.exportFailed": "Unable to export plugin data", "plugins.delete": "Delete data", "plugins.deleteTitle": "Delete this plugin's data?", "plugins.deleteDescription": "This removes records and migration metadata for the current user and installation.", "plugins.deleted": "Plugin data deleted", "plugins.deleteFailed": "Unable to delete plugin data", "plugins.disable": "Disable", "plugins.enable": "Enable", "plugins.uninstall": "Uninstall", "plugins.uninstallTitle": "Uninstall this plugin?", "plugins.uninstallDescription": "The installation is removed from the active runtime, but plugin data remains until explicitly deleted.", "plugins.cancel": "Cancel", "plugins.disabledBeforeUninstall": "Disable the plugin before uninstalling", "plugins.capabilityFailed": "Unable to update capabilities", "plugins.capabilityUpdated": "Capabilities updated", "plugins.disableFailed": "Unable to disable plugin", "plugins.enableFailed": "Unable to enable plugin"
  },
  "zh-CN": {
    "nav.overview": "总览", "nav.plugins": "插件", "nav.jobs": "任务", "nav.history": "历史记录", "nav.catalog": "目录", "nav.speed": "测速", "nav.notifications": "通知", "nav.components": "基础组件", "nav.media": "媒体根目录", "nav.keys": "入口 Key", "nav.security": "安全设置", "nav.users": "用户", "nav.audit": "审计事件", "nav.signOut": "退出登录",
    "login.title": "CarMediaHub Core", "login.subtitle": "登录本地部署。", "login.username": "用户名", "login.password": "密码", "login.otp": "验证器或恢复码", "login.submit": "登录", "login.failed": "登录失败", "login.otpRequired": "请输入验证器代码或恢复码",
    "overview.applications": "应用", "overview.components": "受管组件", "overview.gateway": "网关", "overview.healthy": "健康", "overview.applicationList": "应用列表", "overview.catalog": "受管组件目录", "overview.name": "名称", "overview.category": "分类", "overview.route": "路由", "overview.vehicle": "车机", "overview.supported": "支持", "overview.desktop": "桌面", "overview.component": "组件", "overview.kind": "类型", "overview.version": "版本", "overview.status": "状态", "overview.executable": "可执行文件标识",
    "security.account": "账户安全", "security.authenticator": "验证器", "security.enabled": "已启用", "security.disabled": "未启用", "security.setup": "设置验证器", "security.enabledHint": "验证器保护已启用", "security.enabledDescription": "登录时使用验证器代码或一个未使用的恢复码。", "security.password": "修改密码", "security.currentPassword": "当前密码", "security.newPassword": "新密码", "security.passwordInvalid": "当前密码无效或新密码过短", "security.passwordChanged": "密码已修改，其他会话已退出", "security.preferences": "平台偏好", "security.language": "语言", "security.timeZone": "时区", "security.theme": "主题", "security.density": "密度", "security.system": "跟随系统", "security.light": "浅色", "security.dark": "深色", "security.comfortable": "舒适", "security.compact": "紧凑", "security.updated": "平台偏好已更新", "security.updateFailed": "无法更新平台偏好", "security.setupDescription": "请在验证器应用中录入此密钥，然后确认当前六位代码。", "security.verificationCode": "验证码", "security.sixDigits": "请输入六位验证码", "security.invalidCode": "验证码无效", "security.saveCodes": "保存恢复码", "security.savedCodes": "我已保存这些恢复码", "security.codesWarning": "每个恢复码只能使用一次，之后不会再次显示。",
    "common.add": "添加", "common.list": "列表", "common.component": "组件", "common.components": "组件", "common.version": "版本", "common.executable": "可执行文件", "common.health": "健康状态", "common.action": "操作", "common.check": "检查", "common.revoke": "撤销", "common.status": "状态", "common.kind": "类型", "common.catalog": "目录", "common.platforms": "支持平台", "common.installed": "已安装", "common.serviceBinding": "服务绑定", "common.serviceBindings": "服务绑定", "common.addServiceBinding": "添加服务绑定", "common.serviceBindingCreated": "服务绑定已创建", "common.serviceBindingCreateFailed": "无法创建服务绑定", "common.serviceBindingUnreachable": "服务绑定不可达", "common.serviceBindingRevoked": "服务绑定已撤销", "common.serviceBindingRevokeFailed": "无法撤销服务绑定", "common.reachable": "可达", "common.scope": "作用域", "common.authorizedInstallations": "已授权插件安装实例", "common.pluginInstallation": "插件安装实例", "common.name": "名称", "common.endpoint": "HTTP(S) 端点", "common.coreGlobal": "Core 全局", "common.noneDeclared": "未声明", "common.username": "用户名", "common.temporaryPassword": "临时密码", "common.role": "角色", "common.member": "成员", "common.administrator": "管理员", "common.organizationUsers": "组织用户", "common.locale": "语言", "common.active": "正常", "common.revoked": "已撤销", "common.userAdded": "用户已添加", "common.userAddFailed": "无法添加用户", "common.userRevokeFailed": "无法撤销用户", "common.lastAdmin": "至少需要保留一个管理员", "common.signOut": "退出登录", "common.mediaRoot": "媒体根目录", "common.mediaRoots": "媒体根目录", "common.selectedDirectory": "目录路径", "common.added": "添加时间", "common.mediaRootAdded": "媒体根目录已添加", "common.mediaRootAddFailed": "无法添加媒体根目录", "common.mediaRootRevokeFailed": "无法撤销媒体根目录",
    "plugins.install": "安装插件 Manifest", "plugins.manifest": "Manifest JSON", "plugins.installSuccess": "插件安装已登记", "plugins.manifestRejected": "Manifest 被拒绝", "plugins.invalidJson": "请输入有效的 Manifest JSON", "plugins.list": "插件安装实例", "plugins.package": "包", "plugins.runtime": "运行时", "plugins.capabilities": "已授予能力", "plugins.installation": "安装状态", "plugins.worker": "Worker", "plugins.attempts": "重试次数", "plugins.export": "导出数据", "plugins.exported": "插件数据已导出", "plugins.exportFailed": "无法导出插件数据", "plugins.delete": "删除数据", "plugins.deleteTitle": "删除此插件的数据？", "plugins.deleteDescription": "将删除当前用户和安装实例的数据记录及迁移元数据。", "plugins.deleted": "插件数据已删除", "plugins.deleteFailed": "无法删除插件数据", "plugins.disable": "停用", "plugins.enable": "启用", "plugins.uninstall": "卸载", "plugins.uninstallTitle": "卸载此插件？", "plugins.uninstallDescription": "安装实例会从运行时移除，但插件数据会保留，直到明确删除。", "plugins.cancel": "取消", "plugins.disabledBeforeUninstall": "请先停用插件再卸载", "plugins.capabilityFailed": "无法更新能力", "plugins.capabilityUpdated": "能力已更新", "plugins.disableFailed": "无法停用插件", "plugins.enableFailed": "无法启用插件"
  },
  ko: {
    "nav.overview": "개요", "nav.plugins": "플러그인", "nav.jobs": "작업", "nav.history": "기록", "nav.catalog": "카탈로그", "nav.speed": "속도 테스트", "nav.notifications": "알림", "nav.components": "관리 구성요소", "nav.media": "미디어 루트", "nav.keys": "접속 키", "nav.security": "보안", "nav.users": "사용자", "nav.audit": "감사 이벤트", "nav.signOut": "로그아웃",
    "login.title": "CarMediaHub Core", "login.subtitle": "로컬 배포에 로그인하세요.", "login.username": "사용자 이름", "login.password": "비밀번호", "login.otp": "인증기 또는 복구 코드", "login.submit": "로그인", "login.failed": "로그인 실패", "login.otpRequired": "인증기 코드 또는 복구 코드를 입력하세요",
    "overview.applications": "애플리케이션", "overview.components": "관리 구성요소", "overview.gateway": "게이트웨이", "overview.healthy": "정상", "overview.applicationList": "애플리케이션 목록", "overview.catalog": "관리 구성요소 카탈로그", "overview.name": "이름", "overview.category": "분류", "overview.route": "경로", "overview.vehicle": "차량", "overview.supported": "지원", "overview.desktop": "데스크톱", "overview.component": "구성요소", "overview.kind": "종류", "overview.version": "버전", "overview.status": "상태", "overview.executable": "실행 파일 식별자",
    "security.account": "계정 보안", "security.authenticator": "인증기", "security.enabled": "사용", "security.disabled": "사용 안 함", "security.setup": "인증기 설정", "security.enabledHint": "인증기 보호가 사용 중입니다", "security.enabledDescription": "로그인할 때 인증기 코드 또는 사용하지 않은 복구 코드를 사용하세요.", "security.password": "비밀번호 변경", "security.currentPassword": "현재 비밀번호", "security.newPassword": "새 비밀번호", "security.passwordInvalid": "현재 비밀번호가 잘못되었거나 새 비밀번호가 너무 짧습니다", "security.passwordChanged": "비밀번호가 변경되었고 다른 세션은 로그아웃되었습니다", "security.preferences": "플랫폼 환경설정", "security.language": "언어", "security.timeZone": "시간대", "security.theme": "테마", "security.density": "밀도", "security.system": "시스템 설정", "security.light": "밝게", "security.dark": "어둡게", "security.comfortable": "편안하게", "security.compact": "간결하게", "security.updated": "플랫폼 환경설정이 업데이트되었습니다", "security.updateFailed": "플랫폼 환경설정을 업데이트할 수 없습니다", "security.setupDescription": "인증기 앱에 이 비밀키를 입력한 후 현재 6자리 코드를 확인하세요.", "security.verificationCode": "확인 코드", "security.sixDigits": "6자리 코드를 입력하세요", "security.invalidCode": "확인 코드가 올바르지 않습니다", "security.saveCodes": "복구 코드 저장", "security.savedCodes": "코드를 저장했습니다", "security.codesWarning": "각 복구 코드는 한 번만 사용할 수 있으며 다시 표시되지 않습니다.",
    "common.add": "추가", "common.list": "목록", "common.component": "구성요소", "common.components": "구성요소", "common.version": "버전", "common.executable": "실행 파일", "common.health": "상태", "common.action": "작업", "common.check": "확인", "common.revoke": "취소", "common.status": "상태", "common.kind": "종류", "common.catalog": "카탈로그", "common.platforms": "지원 플랫폼", "common.installed": "설치됨", "common.serviceBinding": "서비스 바인딩", "common.serviceBindings": "서비스 바인딩", "common.addServiceBinding": "서비스 바인딩 추가", "common.serviceBindingCreated": "서비스 바인딩을 생성했습니다", "common.serviceBindingCreateFailed": "서비스 바인딩을 생성할 수 없습니다", "common.serviceBindingUnreachable": "서비스 바인딩에 연결할 수 없습니다", "common.serviceBindingRevoked": "서비스 바인딩을 취소했습니다", "common.serviceBindingRevokeFailed": "서비스 바인딩을 취소할 수 없습니다", "common.reachable": "연결 가능", "common.scope": "범위", "common.authorizedInstallations": "허용된 플러그인 설치", "common.pluginInstallation": "플러그인 설치", "common.name": "이름", "common.endpoint": "HTTP(S) 엔드포인트", "common.coreGlobal": "Core 전역", "common.noneDeclared": "선언 없음", "common.username": "사용자 이름", "common.temporaryPassword": "임시 비밀번호", "common.role": "역할", "common.member": "멤버", "common.administrator": "관리자", "common.organizationUsers": "조직 사용자", "common.locale": "언어", "common.active": "활성", "common.revoked": "취소됨", "common.userAdded": "사용자를 추가했습니다", "common.userAddFailed": "사용자를 추가할 수 없습니다", "common.userRevokeFailed": "사용자를 취소할 수 없습니다", "common.lastAdmin": "최소 한 명의 관리자가 필요합니다", "common.signOut": "로그아웃", "common.mediaRoot": "미디어 루트", "common.mediaRoots": "미디어 루트", "common.selectedDirectory": "디렉터리 경로", "common.added": "추가됨", "common.mediaRootAdded": "미디어 루트를 추가했습니다", "common.mediaRootAddFailed": "미디어 루트를 추가할 수 없습니다", "common.mediaRootRevokeFailed": "미디어 루트를 취소할 수 없습니다",
    "plugins.install": "플러그인 Manifest 설치", "plugins.manifest": "Manifest JSON", "plugins.installSuccess": "플러그인 설치가 등록되었습니다", "plugins.manifestRejected": "Manifest가 거부되었습니다", "plugins.invalidJson": "유효한 Manifest JSON을 입력하세요", "plugins.list": "플러그인 설치", "plugins.package": "패키지", "plugins.runtime": "런타임", "plugins.capabilities": "허용된 기능", "plugins.installation": "설치 상태", "plugins.worker": "Worker", "plugins.attempts": "시도 횟수", "plugins.export": "데이터 내보내기", "plugins.exported": "플러그인 데이터를 내보냈습니다", "plugins.exportFailed": "플러그인 데이터를 내보낼 수 없습니다", "plugins.delete": "데이터 삭제", "plugins.deleteTitle": "이 플러그인의 데이터를 삭제할까요?", "plugins.deleteDescription": "현재 사용자와 설치 인스턴스의 레코드 및 마이그레이션 메타데이터를 삭제합니다.", "plugins.deleted": "플러그인 데이터를 삭제했습니다", "plugins.deleteFailed": "플러그인 데이터를 삭제할 수 없습니다", "plugins.disable": "사용 안 함", "plugins.enable": "사용", "plugins.uninstall": "제거", "plugins.uninstallTitle": "이 플러그인을 제거할까요?", "plugins.uninstallDescription": "설치 인스턴스는 런타임에서 제거되지만 데이터를 명시적으로 삭제할 때까지 보존됩니다.", "plugins.cancel": "취소", "plugins.disabledBeforeUninstall": "제거하기 전에 플러그인을 사용하지 않도록 설정하세요", "plugins.capabilityFailed": "기능을 업데이트할 수 없습니다", "plugins.capabilityUpdated": "기능이 업데이트되었습니다", "plugins.disableFailed": "플러그인을 사용하지 않도록 설정할 수 없습니다", "plugins.enableFailed": "플러그인을 사용할 수 없습니다"
  }
} as const;

export type Translator = (key: MessageKey) => string;
export const AdminI18nContext = createContext<{ locale: AdminLocale; t: Translator }>({ locale: "en", t: (key) => messages.en[key] });
export function translate(locale: AdminLocale, key: MessageKey): string { return messages[locale][key] ?? messages.en[key]; }
export function useAdminI18n(): { locale: AdminLocale; t: Translator } { return useContext(AdminI18nContext); }
