// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'E:/projects/mine/CarMediaHub/carmediahub/admin/src/.umi-production/plugin-access';
export { Provider, useModel } from 'E:/projects/mine/CarMediaHub/carmediahub/admin/src/.umi-production/plugin-model';
// plugins types.d.ts
export * from 'E:/projects/mine/CarMediaHub/carmediahub/admin/src/.umi-production/plugin-access/types.d';
export * from 'E:/projects/mine/CarMediaHub/carmediahub/admin/src/.umi-production/plugin-antd/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'E:/projects/mine/CarMediaHub/carmediahub/admin/node_modules/.pnpm/@umijs+renderer-react@4.7.1_45c565656ddcff7643cea146df2188b8/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from 'E:/projects/mine/CarMediaHub/carmediahub/admin/node_modules/.pnpm/@umijs+renderer-react@4.7.1_45c565656ddcff7643cea146df2188b8/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'E:/projects/mine/CarMediaHub/carmediahub/admin/node_modules/.pnpm/umi@4.7.19_@babel+core@7.29_41cad0d868bcfc1a4f8899a00bf20745/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
