// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from 'E:/projects/mine/CarMediaHub/carmediahub/admin/node_modules/.pnpm/@umijs+renderer-react@4.7.1_45c565656ddcff7643cea146df2188b8/node_modules/@umijs/renderer-react';
import { context } from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
}
