import { AppstoreOutlined, CloudServerOutlined, FolderOpenOutlined, KeyOutlined, LogoutOutlined, SafetyCertificateOutlined, TeamOutlined, ThunderboltOutlined, UnorderedListOutlined, ChromeOutlined } from "@ant-design/icons";
import { ProCard, ProLayout, ProTable } from "@ant-design/pro-components";
import { Button, message, Popconfirm, Space, Tag } from "antd";
import { useEffect, useState } from "react";

type BrowserSession = { id: string; name: string; purpose: string; status: string; expiresAt: string; userId: string; installationId: string };
type BrowserTask = { id: string; sessionId: string; kind: string; status: string; createdAt: string; updatedAt: string; userId: string; installationId: string };
const routes = [{ path: "/admin/overview", name: "Overview", icon: <AppstoreOutlined /> }, { path: "/admin/plugins", name: "Plugins", icon: <ThunderboltOutlined /> }, { path: "/admin/jobs", name: "Tasks", icon: <UnorderedListOutlined /> }, { path: "/admin/browser", name: "Browser", icon: <ChromeOutlined /> }, { path: "/admin/components", name: "Components", icon: <CloudServerOutlined /> }, { path: "/admin/media", name: "Media roots", icon: <FolderOpenOutlined /> }, { path: "/admin/keys", name: "Entry keys", icon: <KeyOutlined /> }, { path: "/admin/security", name: "Security", icon: <SafetyCertificateOutlined /> }, { path: "/admin/users", name: "Users", icon: <TeamOutlined /> }];

export default function Browser() {
  const [sessions, setSessions] = useState<BrowserSession[]>([]);
  const [tasks, setTasks] = useState<BrowserTask[]>([]);
  const refresh = () => { void Promise.all([fetch("/api/browser/sessions"), fetch("/api/browser/tasks")]).then(async ([sessionResponse, taskResponse]) => { const sessionData = sessionResponse.ok ? await sessionResponse.json() : { sessions: [] }; const taskData = taskResponse.ok ? await taskResponse.json() : { tasks: [] }; setSessions(sessionData.sessions ?? []); setTasks(taskData.tasks ?? []); }); };
  useEffect(refresh, []);
  const logout = async () => { await fetch("/api/auth/logout", { method: "POST" }); window.location.href = "/admin/login"; };
  return <ProLayout title="CarMediaHub" logo={false} route={{ routes }} location={{ pathname: "/admin/browser" }} menuItemRender={(item, dom) => <a href={item.path}>{dom}</a>} actionsRender={() => [<Button key="logout" icon={<LogoutOutlined />} onClick={() => void logout()}>Sign out</Button>]}> 
    <ProCard title="Browser sessions" style={{ margin: 24 }}><ProTable<BrowserSession> rowKey="id" search={false} options={{ reload: refresh }} dataSource={sessions} columns={[{ title: "Name", dataIndex: "name" }, { title: "Purpose", dataIndex: "purpose" }, { title: "User", dataIndex: "userId" }, { title: "Plugin", dataIndex: "installationId" }, { title: "Status", dataIndex: "status", render: (value) => <Tag color={value === "active" ? "green" : "default"}>{value}</Tag> }, { title: "Expires", dataIndex: "expiresAt" }, { title: "Action", render: (_, row) => <Popconfirm title="Revoke this browser session?" onConfirm={async () => { const response = await fetch(`/api/browser/sessions/${row.id}/revoke`, { method: "POST" }); if (!response.ok) { message.error("Unable to revoke session"); return; } message.success("Session revoked"); refresh(); }}><Button danger disabled={row.status !== "active"}>Revoke</Button></Popconfirm> }]} /></ProCard>
    <ProCard title="Browser tasks" style={{ margin: 24 }}><ProTable<BrowserTask> rowKey="id" search={false} options={false} dataSource={tasks} columns={[{ title: "Kind", dataIndex: "kind" }, { title: "Session", dataIndex: "sessionId" }, { title: "User", dataIndex: "userId" }, { title: "Plugin", dataIndex: "installationId" }, { title: "Status", dataIndex: "status", render: (value) => <Tag color={value === "running" ? "blue" : value === "failed" ? "red" : value === "succeeded" ? "green" : "default"}>{value}</Tag> }, { title: "Created", dataIndex: "createdAt" }, { title: "Action", render: (_, row) => <Space><Button danger disabled={!(row.status === "queued" || row.status === "running")} onClick={async () => { const response = await fetch(`/api/browser/tasks/${row.id}/cancel`, { method: "POST" }); if (!response.ok) { message.error("Unable to cancel task"); return; } message.success("Task cancelled"); refresh(); }}>Cancel</Button></Space> }]} /></ProCard>
  </ProLayout>;
}
