import { AppstoreOutlined, CloudServerOutlined, DatabaseOutlined, FolderOpenOutlined, KeyOutlined, LogoutOutlined, SafetyCertificateOutlined, TeamOutlined } from "@ant-design/icons";
import { ProCard, ProForm, ProFormSelect, ProFormText, ProLayout, ProTable } from "@ant-design/pro-components";
import { Button, message, Popconfirm, Space, Tag } from "antd";
import { useEffect, useState } from "react";

type Source = { sourceHandle: string; name: string; binding: string; createdAt: string };
type Installation = { id: string; packageId: string; packageVersion: string; status: string };
type Credential = { id: string; name: string; kind: string; installationId: string };

const routes = [{ path: "/admin/overview", name: "Overview", icon: <AppstoreOutlined /> }, { path: "/admin/components", name: "Components", icon: <CloudServerOutlined /> }, { path: "/admin/media", name: "Media roots", icon: <FolderOpenOutlined /> }, { path: "/admin/media-sources", name: "Remote media sources", icon: <DatabaseOutlined /> }, { path: "/admin/keys", name: "Entry keys", icon: <KeyOutlined /> }, { path: "/admin/security", name: "Security", icon: <SafetyCertificateOutlined /> }, { path: "/admin/users", name: "Users", icon: <TeamOutlined /> }];

export default function MediaSources() {
  const [sources, setSources] = useState<Source[]>([]);
  const [installations, setInstallations] = useState<Installation[]>([]);
  const [credentials, setCredentials] = useState<Credential[]>([]);
  const [selectedInstallation, setSelectedInstallation] = useState<string>();
  const refresh = () => { if (selectedInstallation === undefined) return; void fetch(`/api/media-sources?installationId=${encodeURIComponent(selectedInstallation)}`).then(async (response) => response.ok ? response.json() : { sources: [] }).then((data) => setSources(data.sources ?? [])); };
  useEffect(() => { void Promise.all([fetch("/api/plugins"), fetch("/api/credentials")]).then(async ([pluginsResponse, credentialsResponse]) => { const plugins = pluginsResponse.ok ? await pluginsResponse.json() : { installations: [] }; const stored = credentialsResponse.ok ? await credentialsResponse.json() : { credentials: [] }; const installed = (plugins.installations ?? []).filter((item: Installation) => item.status === "installed"); setInstallations(installed); setCredentials(stored.credentials ?? []); if (selectedInstallation === undefined && installed[0] !== undefined) setSelectedInstallation(installed[0].id); }); }, []);
  useEffect(() => { refresh(); }, [selectedInstallation]);
  return <ProLayout title="CarMediaHub" logo={false} route={{ routes }} location={{ pathname: "/admin/media-sources" }} menuItemRender={(item, dom) => <a href={item.path}>{dom}</a>} actionsRender={() => [<Button key="logout" icon={<LogoutOutlined />} onClick={async () => { await fetch("/api/auth/logout", { method: "POST" }); window.location.href = "/admin/login"; }}>Sign out</Button>]}> 
    <ProCard title="Add remote media source" style={{ margin: 24 }}><ProForm layout="inline" onFinish={async (values) => { const response = await fetch("/api/media-sources", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); if (!response.ok) { message.error("Unable to add media source"); return false; } message.success("Media source added"); setSelectedInstallation(values.installationId); refresh(); return true; }}><ProFormSelect name="installationId" label="Plugin installation" fieldProps={{ onChange: setSelectedInstallation }} options={installations.map((item) => ({ label: `${item.packageId} (${item.id})`, value: item.id }))} rules={[{ required: true }]} /><ProFormText name="name" label="Name" rules={[{ required: true, max: 80 }]} /><ProFormText name="binding" label="Binding" rules={[{ required: true, pattern: /^[a-z][a-z0-9-]{0,63}$/u }]} /><ProFormText name="rootPath" label="Remote root path" placeholder="/dav/" rules={[{ required: true }]} /><ProFormSelect name="credentialRef" label="Credential" allowClear options={credentials.filter((item) => item.installationId === selectedInstallation).map((item) => ({ label: `${item.name} (${item.kind})`, value: item.id }))} /></ProForm></ProCard>
    <ProCard title="Registered remote media sources" style={{ margin: 24 }}><ProTable<Source> rowKey="sourceHandle" search={false} options={{ reload: refresh }} dataSource={sources} columns={[{ title: "Name", dataIndex: "name" }, { title: "Binding", dataIndex: "binding" }, { title: "Handle", dataIndex: "sourceHandle", render: (value) => <Tag>{String(value).slice(0, 18)}...</Tag> }, { title: "Added", dataIndex: "createdAt" }, { title: "Action", render: (_, row) => <Space><Button onClick={async () => { const response = await fetch(`/api/media-sources/${encodeURIComponent(row.sourceHandle)}/health?installationId=${encodeURIComponent(selectedInstallation ?? "")}`, { method: "POST" }); const result = response.ok ? await response.json() as { healthy: boolean; diagnostic: string } : undefined; if (result?.healthy) message.success("Remote source is healthy"); else message.error(`Remote source unavailable (${result?.diagnostic ?? "unknown"})`); }}>Check</Button><Popconfirm title="Revoke this remote media source?" onConfirm={async () => { const response = await fetch(`/api/media-sources/${encodeURIComponent(row.sourceHandle)}/revoke?installationId=${encodeURIComponent(selectedInstallation ?? "")}`, { method: "POST" }); if (!response.ok) { message.error("Unable to revoke media source"); return; } message.success("Media source revoked"); refresh(); }}><Button danger>Revoke</Button></Popconfirm></Space> }]} /></ProCard>
  </ProLayout>;
}
