minimumReleaseAgeExclude:
  - '@umijs/ast@4.7.19'
  - '@umijs/babel-preset-umi@4.7.19'
  - '@umijs/bundler-esbuild@4.7.19'
  - '@umijs/bundler-utils@4.7.19'
  - '@umijs/bundler-utoopack@4.7.19'
  - '@umijs/bundler-vite@4.7.19'
  - '@umijs/bundler-webpack@4.7.19'
  - '@umijs/core@4.7.19'
  - '@umijs/lint@4.7.19'
  - '@umijs/max@4.7.19'
  - '@umijs/mfsu@4.7.19'
  - '@umijs/plugin-run@4.7.19'
  - '@umijs/plugins@4.7.19'
  - '@umijs/preset-umi@4.7.19'
  - '@umijs/renderer-react@4.7.19'
  - '@umijs/server@4.7.19'
  - '@umijs/test@4.7.19'
  - '@umijs/utils@4.7.19'
  - '@umijs/zod2ts@4.7.19'
  - umi@4.7.19
