import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { BrowserTaskExecutor } from "./browser-task-executor.js";
import { openDatabase } from "./database.js";
import { Repository } from "./repository.js";

const scope = { deploymentId: "dep", organizationId: "org", userId: "user", deviceId: "vehicle", sessionId: "session", installationId: "plugin" };
function setup() { const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "cmh-browser-task-")); const database = openDatabase(dataDir); const repository = new Repository(database.db, Buffer.alloc(32, 7)); repository.bootstrap("admin", "correct horse battery staple", "en"); const user = database.db.prepare("SELECT id, organization_id FROM users LIMIT 1").get() as { id: string; organization_id: string }; const currentScope = { ...scope, organizationId: user.organization_id, userId: user.id }; repository.createBrowserSession(currentScope, { name: "fixture", purpose: "test", ttlSeconds: 300 }); const session = repository.browserSessions(currentScope)[0]!; const task = repository.createBrowserTask(currentScope, { sessionId: session.id, kind: "navigate-and-capture", input: { target: "fixture" } }); return { dataDir, database, repository, task, scope: currentScope }; }

test("browser task executor persists only bounded structured results", async () => { const { dataDir, database, repository, task, scope: currentScope } = setup(); try { const executor = new BrowserTaskExecutor(repository); executor.register("navigate-and-capture", async () => ({ kind: "navigate-and-capture", fields: { page_title: "Fixture", status: 200 }, expiresAt: new Date(Date.now() + 60_000).toISOString() }), { allowedTargets: ["fixture"] }); const completed = await executor.runUntilIdle(currentScope); assert.equal(completed[0]?.result?.fields?.page_title, "Fixture"); assert.equal(repository.browserTasks(currentScope)[0]?.result?.fields?.status, 200); } finally { database.close(); fs.rmSync(dataDir, { recursive: true, force: true }); } });
test("browser task executor rejects sensitive or unbounded results", async () => { const { dataDir, database, repository, task, scope: currentScope } = setup(); try { const executor = new BrowserTaskExecutor(repository); executor.register("navigate-and-capture", async () => ({ kind: "navigate-and-capture", fields: { cookieHeader: "blocked" }, expiresAt: new Date(Date.now() + 60_000).toISOString() }), { allowedTargets: ["fixture"] }); const completed = await executor.runUntilIdle(currentScope); assert.equal(completed[0]?.status, "failed"); assert.equal(repository.browserTasks(currentScope)[0]?.result, undefined); } finally { database.close(); fs.rmSync(dataDir, { recursive: true, force: true }); } });
test("browser task executor claims, completes and batches only registered work", async () => { const { dataDir, database, repository, task, scope: currentScope } = setup(); try { const executor = new BrowserTaskExecutor(repository); const seen: string[] = []; executor.register("navigate-and-capture", async (current, handlerScope, signal) => { assert.equal(handlerScope.installationId, "plugin"); assert.equal(signal.aborted, false); seen.push(current.id); }, { allowedTargets: ["fixture"] }); const completed = await executor.runUntilIdle(currentScope); assert.deepEqual(seen, [task.id]); assert.equal(completed[0]?.status, "succeeded"); assert.equal(repository.browserTasks(currentScope)[0]?.status, "succeeded"); } finally { database.close(); fs.rmSync(dataDir, { recursive: true, force: true }); } });
test("browser task executor aborts active handlers and persists cancellation", async () => { const { dataDir, database, repository, task, scope: currentScope } = setup(); try { const executor = new BrowserTaskExecutor(repository); let aborted = false; executor.register("navigate-and-capture", (_task, _scope, signal) => new Promise<void>((resolve) => { signal.addEventListener("abort", () => { aborted = true; resolve(); }, { once: true }); }), { allowedTargets: ["fixture"] }); const running = executor.runOnce(currentScope); await new Promise((resolve) => setImmediate(resolve)); assert.equal(executor.cancel(currentScope, task.id)?.status, "cancelled"); await running; assert.equal(aborted, true); assert.equal(repository.browserTasks(currentScope)[0]?.status, "cancelled"); } finally { database.close(); fs.rmSync(dataDir, { recursive: true, force: true }); } });

test("browser task executor fails targets outside the registered allowlist before invoking a handler", async () => { const { dataDir, database, repository, task, scope: currentScope } = setup(); try { repository.cancelBrowserTask(currentScope, task.id); const session = repository.browserSessions(currentScope)[0]!; repository.createBrowserTask(currentScope, { sessionId: session.id, kind: "navigate-and-capture", input: { target: "other-target" } }); const executor = new BrowserTaskExecutor(repository); let invoked = false; executor.register("navigate-and-capture", () => { invoked = true; }, { allowedTargets: ["fixture"] }); const result = await executor.runOnce(currentScope); assert.equal(invoked, false); assert.equal(result?.status, "failed"); } finally { database.close(); fs.rmSync(dataDir, { recursive: true, force: true }); } });

test("browser task executor cancels every active task in a session", async () => { const { dataDir, database, repository, task, scope: currentScope } = setup(); try { const executor = new BrowserTaskExecutor(repository); let aborted = false; executor.register("navigate-and-capture", (_task, _scope, signal) => new Promise<void>((resolve) => signal.addEventListener("abort", () => { aborted = true; resolve(); }, { once: true })), { allowedTargets: ["fixture"] }); const running = executor.runOnce(currentScope); await new Promise((resolve) => setImmediate(resolve)); assert.equal(executor.cancelSession(currentScope, task.sessionId), 1); await running; assert.equal(aborted, true); } finally { database.close(); fs.rmSync(dataDir, { recursive: true, force: true }); } });

test("browser task executor cancels installation tasks across user scopes", async () => { const { dataDir, database, repository, task, scope: currentScope } = setup(); try { const executor = new BrowserTaskExecutor(repository); let aborted = false; executor.register("navigate-and-capture", (_task, _scope, signal) => new Promise<void>((resolve) => signal.addEventListener("abort", () => { aborted = true; resolve(); }, { once: true })), { allowedTargets: ["fixture"] }); const running = executor.runOnce(currentScope); await new Promise((resolve) => setImmediate(resolve)); assert.equal(executor.cancelInstallation(currentScope.organizationId, currentScope.installationId), 1); await running; assert.equal(aborted, true); assert.equal(repository.browserTasks(currentScope).find((item) => item.id === task.id)?.status, "cancelled"); } finally { database.close(); fs.rmSync(dataDir, { recursive: true, force: true }); } });
